insert into brand(value, name) values(4,"ألفا روميو");
insert into brand(value, name) values(32,"أوبل");
insert into brand(value, name) values(5,"أودي");
insert into brand(value, name) values(80,"أيديا");
insert into brand(value, name) values(20,"إيسوزو");
insert into brand(value, name) values(60,"اسبيرانزا");
insert into brand(value, name) values(97,"استون مارتن");
insert into brand(value, name) values(91,"ام جي");
insert into brand(value, name) values(84,"انفنتي");
insert into brand(value, name) values(103,"ايجل");
insert into brand(value, name) values(36,"بروتون");
insert into brand(value, name) values(68,"بريليانس");
insert into brand(value, name) values(87,"بنتلي");
insert into brand(value, name) values(35,"بورش");
insert into brand(value, name) values(53,"بونتياك");
insert into brand(value, name) values(66,"بويك");
insert into brand(value, name) values(6,"بي إم دبليو");
insert into brand(value, name) values(71,"بي واي دي");
insert into brand(value, name) values(34,"بيجو");
insert into brand(value, name) values(33,"بيرودوا");
insert into brand(value, name) values(47,"تويوتا");
insert into brand(value, name) values(21,"جاجوار");
insert into brand(value, name) values(88,"جاك");
insert into brand(value, name) values(72,"جريت وول");
insert into brand(value, name) values(17,"جي إم سي");
insert into brand(value, name) values(22,"جيب");
insert into brand(value, name) values(59,"جيلي");
insert into brand(value, name) values(94,"جين بى");
insert into brand(value, name) values(11,"داتشيا");
insert into brand(value, name) values(13,"دايهاتسو");
insert into brand(value, name) values(12,"دايو");
insert into brand(value, name) values(14,"دودج");
insert into brand(value, name) values(83,"روفر");
insert into brand(value, name) values(38,"رولز رويس");
insert into brand(value, name) values(37,"رينو");
insert into brand(value, name) values(89,"زوتي");
insert into brand(value, name) values(40,"ساب");
insert into brand(value, name) values(41,"سامسونج");
insert into brand(value, name) values(70,"سانجيونج");
insert into brand(value, name) values(100,"ساويست");
insert into brand(value, name) values(96,"سايبا");
insert into brand(value, name) values(8,"ستروين");
insert into brand(value, name) values(43,"سكودا");
insert into brand(value, name) values(44,"سمارت");
insert into brand(value, name) values(45,"سوبارو");
insert into brand(value, name) values(46,"سوزوكي");
insert into brand(value, name) values(42,"سيات");
insert into brand(value, name) values(101,"سينوفا");
insert into brand(value, name) values(92,"شانا");
insert into brand(value, name) values(90,"شانجان");
insert into brand(value, name) values(51,"شاهين");
insert into brand(value, name) values(58,"شيري");
insert into brand(value, name) values(9,"شيفروليه");
insert into brand(value, name) values(95,"فاو");
insert into brand(value, name) values(16,"فورد");
insert into brand(value, name) values(49,"فولفو");
insert into brand(value, name) values(48,"فولكس فاجن");
insert into brand(value, name) values(15,"فيات");
insert into brand(value, name) values(93,"فيراري");
insert into brand(value, name) values(7,"كاديلاك");
insert into brand(value, name) values(10,"كرايسلر");
insert into brand(value, name) values(78,"كومودو");
insert into brand(value, name) values(23,"كيا");
insert into brand(value, name) values(64,"لادا");
insert into brand(value, name) values(39,"لاند روفر");
insert into brand(value, name) values(24,"لانشيا");
insert into brand(value, name) values(25,"لكزس");
insert into brand(value, name) values(86,"ليفان");
insert into brand(value, name) values(26,"لينكولن");
insert into brand(value, name) values(74,"مابل");
insert into brand(value, name) values(27,"مازدا");
insert into brand(value, name) values(98,"مازيراتي");
insert into brand(value, name) values(76,"ماهيندرا");
insert into brand(value, name) values(28,"مرسيدس");
insert into brand(value, name) values(29,"ميتسوبيشي");
insert into brand(value, name) values(77,"ميركوري");
insert into brand(value, name) values(67,"ميني");
insert into brand(value, name) values(79,"نوبل");
insert into brand(value, name) values(31,"نيسان");
insert into brand(value, name) values(63,"هافي");
insert into brand(value, name) values(69,"هامر");
insert into brand(value, name) values(102,"هاوتاي");
insert into brand(value, name) values(75,"هايما");
insert into brand(value, name) values(1,"هوندا");
insert into brand(value, name) values(19,"هيونداي");